# Generated by Django 5.2.7 on 2025-10-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargos',
            name='nome',
            field=models.CharField(default=50, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cargos',
            name='id',
            field=models.IntegerField(choices=[(1, 'GM'), (2, 'Gerente'), (3, 'Administrativo'), (4, 'Operador')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.IntegerField(choices=[(1, 'GM'), (2, 'Gerente'), (3, 'Administrativo'), (4, 'Operador')], default=4),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='re',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
