# Generated by Django 5.2.7 on 2025-10-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0002_cargos_nome_alter_cargos_id_alter_perfil_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargos',
            name='nome',
        ),
        migrations.AlterField(
            model_name='cargos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
