# Generated by Django 5.2.6 on 2025-10-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0003_remove_cargos_nome_alter_cargos_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargos',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(choices=[(1, 'GM'), (2, 'Gerente'), (3, 'Administrativo'), (4, 'Operador')], default=4, max_length=14),
        ),
    ]
