# Generated by Django 5.2.7 on 2025-10-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0004_delete_cargos_alter_perfil_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(
                choices=[
                    ('administrador', 'Administrador'),
                    ('gerente', 'Gerente'),
                    ('administrativo', 'Administrativo'),
                    ('operador', 'Operador'),
                ],
                default='operador',
                max_length=14
            ),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
