# Generated by Django 5.2.7 on 2025-10-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0009_alter_aguacloro_data_hora_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diariobordo',
            options={'ordering': ['-data', '-turno'], 'verbose_name': 'Diário de Bordo', 'verbose_name_plural': 'Diários de Bordo'},
        ),
        migrations.RemoveField(
            model_name='diariobordo',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='autonoma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='laminadora_parada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='manutencao_eletrica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='manutencao_mecanica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='maquina_disponivel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='maquina_rodando',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='material_insuficiente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='ocorrencias_turno',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='outros',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='presenca_materiais_estranhos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='preventiva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='quebra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='re',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='troca_faca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='troca_tela',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diariobordo',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diariobordo',
            name='turno',
            field=models.CharField(blank=True, choices=[('1', 'Turno 1'), ('2', 'Turno 2'), ('3', 'Turno 3')], max_length=1, null=True),
        ),
    ]
