# Generated by Django 5.2.7 on 2025-10-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0010_alter_diariobordo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aguacloro',
            options={'verbose_name': 'Água/Cloro', 'verbose_name_plural': 'Água/Cloro'},
        ),
        migrations.RemoveField(
            model_name='aguacloro',
            name='nivel_cloro',
        ),
        migrations.RemoveField(
            model_name='aguacloro',
            name='ph_agua',
        ),
        migrations.AddField(
            model_name='aguacloro',
            name='cloro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Cloro'),
        ),
        migrations.AddField(
            model_name='aguacloro',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='aguacloro',
            name='re',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aguacloro',
            name='turbidez',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Turbidez'),
        ),
        migrations.AddField(
            model_name='aguacloro',
            name='turno',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
