# Generated by Django 5.2.7 on 2025-10-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0011_alter_aguacloro_options_remove_aguacloro_nivel_cloro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='force_password_reset',
            field=models.BooleanField(default=False),
        ),
    ]
