# Generated by Django 5.2.7 on 2025-10-08 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0012_perfil_force_password_reset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariobordo',
            name='maquina_disponivel',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diariobordo',
            name='maquina_rodando',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CarregamentoDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('empresa', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído')], default='pendente', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('concluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carregamento Dashboard',
                'verbose_name_plural': 'Carregamentos Dashboard',
                'ordering': ['data', 'data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ProducaoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('turno', models.CharField(choices=[('1', 'Turno 1'), ('2', 'Turno 2'), ('3', 'Turno 3')], max_length=1)),
                ('total_fardo', models.IntegerField(default=0)),
                ('total_reversao', models.IntegerField(default=0)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produção Mensal',
                'verbose_name_plural': 'Produções Mensais',
                'ordering': ['ano', 'mes', 'turno'],
                'unique_together': {('mes', 'ano', 'turno')},
            },
        ),
    ]
