# Generated by Django 5.2.7 on 2025-10-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0014_carregamentodashboard_criado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='sobrenome',
            field=models.CharField(blank=True, default='', max_length=124),
        ),
    ]
