# Generated by Django 5.2.7 on 2025-10-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0015_perfil_sobrenome'),
    ]

    operations = [
        migrations.AddField(
            model_name='diariobordo',
            name='maquina_parada',
            field=models.BooleanField(default=False),
        ),
    ]
