# Generated by Django 5.2.7 on 2025-10-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0016_diariobordo_maquina_parada'),
    ]

    operations = [
        migrations.AddField(
            model_name='carregamentodashboard',
            name='maquina_parada',
            field=models.BooleanField(default=False),
        ),
    ]
