# Generated by Django 5.2.7 on 2025-10-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0017_carregamentodashboard_maquina_parada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carregamentodashboard',
            name='maquina_parada',
        ),
    ]
