# Generated by Django 5.2.7 on 2025-10-08 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0018_remove_carregamentodashboard_maquina_parada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carregamentodashboard',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carregamentos_cancelados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carregamentodashboard',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carregamentodashboard',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=10),
        ),
    ]
