# Generated by Django 5.2.7 on 2025-10-10 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0019_carregamentodashboard_cancelado_por_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plil',
        ),
    ]
