# Generated by Django 5.2.7 on 2025-10-10 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0020_delete_old_plil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('periodicidade', models.CharField(choices=[('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal')], max_length=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='plil_templates/')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de Tarefa',
                'verbose_name_plural': 'Templates de Tarefas',
            },
        ),
        migrations.CreateModel(
            name='Plil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_responsavel', models.CharField(max_length=24)),
                ('nome_responsavel', models.CharField(max_length=124)),
                ('data_prevista', models.DateField()),
                ('data_execucao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('executada', 'Executada'), ('atrasada', 'Atrasada')], default='pendente', max_length=10)),
                ('observacoes_execucao', models.TextField(blank=True)),
                ('data_atribuicao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atribuida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prs.tarefatemplate')),
            ],
            options={
                'verbose_name': 'Tarefa PLIL',
                'verbose_name_plural': 'Tarefas PLIL',
                'ordering': ['data_prevista', 'status'],
            },
        ),
    ]
